default: &default
  adapter: mysql2
  username: root
  password: pizza
  socket: /home/mysql_data/mysqld.sock

development:
  <<: *default
  database: drunken_tomatoes

test:
  <<: *default
  database: drunken_tomatoes_test

production:
  <<: *default
  database: drunken_tomatoes
